name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/trading-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/trading-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Backend metadata (tags: latest + commit SHA)
      - name: Extract backend metadata
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.BACKEND_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}

      # Frontend metadata (tags: latest + commit SHA)
      - name: Extract frontend metadata
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FRONTEND_IMAGE }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}

      # Optional: Trigger remote deploy (e.g., Render, Fly.io)
      - name: Trigger remote deploy
        if: secrets.RENDER_DEPLOY_HOOK != ''
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
