name: Smoke Test (Fast Feedback + Auto‑Commit Safeguard)

on:
  push:
    branches-ignore:
      - main   # ✅ Don't run Smoke Test on direct pushes to main
    paths-ignore:
      - '.github/workflows/full-matrix.yml'  # avoid loops
      - 'requirements.txt'                   # avoid retriggering Full Matrix

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'
          channels: conda-forge,defaults
          activate-environment: base

      - name: Cache Conda environment
        id: conda-cache
        uses: actions/cache@v4.2.4
        with:
          path: ~/conda_env_smoke
          key: ${{ runner.os }}-conda-env-smoke-${{ hashFiles('environment-dev.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-env-smoke-

      - name: Create/Update Conda environment
        if: steps.conda-cache.outputs.cache-hit != 'true'
        run: |
          conda env create --prefix ~/conda_env_smoke --file environment-dev.yml || \
          conda env update --prefix ~/conda_env_smoke --file environment-dev.yml --prune

      - name: Activate Conda environment
        run: conda activate ~/conda_env_smoke

      - name: Check for missing imports
        run: |
          conda activate ~/conda_env_smoke
          pip install pipreqs
          pipreqs --force --ignore .github --savepath temp-reqs.txt
          MISSING=0
          while read -r pkg; do
            if ! pip show "$(echo $pkg | cut -d'=' -f1)" > /dev/null 2>&1; then
              echo "❌ Missing package: $pkg"
              MISSING=1
            fi
          done < temp-reqs.txt
          if [ $MISSING -eq 1 ]; then
            exit 1
          fi

      - name: Export requirements.txt
        run: |
          conda activate ~/conda_env_smoke
          pip freeze > requirements.txt

      - name: Commit updated requirements.txt
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "ci: sync requirements.txt from environment-dev.yml [skip ci]"
          file_pattern: requirements.txt
          branch: ${{ github.head_ref || github.ref_name }}

      - name: Lint and Unit Tests
        run: |
          conda activate ~/conda_env_smoke
          conda install flake8 pytest
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          pytest tests/unit
